#!/bin/bash
source msgUtil

isNumber() {
   export VAR=$1
   python3 -c 'import inputValidator, os; inputValidator.isNumberEx(os.environ["VAR"])'
   return $?
}

isValidEmail() {
   export VAR=$1
   python3 -c 'import inputValidator, os; inputValidator.isValidEmailEx(os.environ["VAR"])'
   return $?
}

if isValidEmail "vpeevski@discoverita.com"; then
	printSucc "Yes" 
else
    printErr "No"
fi